name: CI

on:

  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./astroCal

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: npm install
        run: npm install
        
      - name: npm run bundle
        run: npm run bundle

      - name: FTP Deploy AstroCal (Podruction)
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.erickribeiro.me
          ftp-username: admin@astrocal.dev
          ftp-password: ${{ secrets.PROD_FTP_PASSWORD }}
          port: 21
          local-dir: ./astroCal
